title: Madhav's Blog
author: "Madhav Tummala"
email: madhavtummala@icloud.com

theme: minima

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  # date format familiar to indians
  date_format: "%b %d, %Y"
  # dark mode because for real developers ðŸ˜œ
  skin: dark
  # Minima social links
  social_links:
    linkedin: madhav-tummala-115984145
    youtube_channel: UCA95U4gtPPz-2XKNZzc2inA
    instagram: madhavtummala
    twitter_username: madhavtummala
    github_username: madhavtummala
    gitlab: MadhavTummala

# Who doesn't want better indexing
plugins:
  - jekyll-feed
  - jekyll-seo-tag


discuss:
  # for a comment section
  shortname: madhavtummala

# Minima: custom header links
header_pages:
  - _pages/about.md
  - _pages/archive.md

# these are the place for all the blog posts
include:
    - _pages

# these things better not appear on the page
exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md